# Generated by Django 2.2.10 on 2020-02-28 22:53

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=team.models.image_folder)),
                ('slug', models.SlugField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
